# Generated by Django 4.1.2 on 2022-10-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
